// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Models;

namespace WebApplication.Migrations
{
    [DbContext(typeof(DbMusicContext))]
    [Migration("20220722215740_Update2")]
    partial class Update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("IdMusicLabel")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdMusicLabel");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            IdAlbum = 1,
                            AlbumName = "You",
                            IdMusicLabel = 1,
                            PublishDate = new DateTime(1998, 7, 13, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdAlbum = 2,
                            AlbumName = "Summer",
                            IdMusicLabel = 1,
                            PublishDate = new DateTime(1999, 2, 4, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            IdAlbum = 3,
                            AlbumName = "Good vibes",
                            IdMusicLabel = 3,
                            PublishDate = new DateTime(1996, 9, 2, 1, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApplication.Models.MusicLabel", b =>
                {
                    b.Property<int>("IdMusicLabel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdMusicLabel");

                    b.ToTable("MusicLabel");

                    b.HasData(
                        new
                        {
                            IdMusicLabel = 1,
                            Name = "MusicAllDay"
                        },
                        new
                        {
                            IdMusicLabel = 2,
                            Name = "OnlyMusic"
                        },
                        new
                        {
                            IdMusicLabel = 3,
                            Name = "LoveMusic"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Musician", b =>
                {
                    b.Property<int>("IdMusician")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("IdMusician");

                    b.ToTable("Musician");

                    b.HasData(
                        new
                        {
                            IdMusician = 1,
                            FirstName = "John",
                            LastName = "Smith",
                            NickName = "jsmith"
                        },
                        new
                        {
                            IdMusician = 2,
                            FirstName = "Franklin",
                            LastName = "Ward",
                            NickName = "frank"
                        },
                        new
                        {
                            IdMusician = 3,
                            FirstName = "Tom",
                            LastName = "Blake",
                            NickName = "TB"
                        },
                        new
                        {
                            IdMusician = 4,
                            FirstName = "Kim",
                            LastName = "White",
                            NickName = "WhiteK"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Musician_Track", b =>
                {
                    b.Property<int>("IdTrack")
                        .HasColumnType("int");

                    b.Property<int>("IdMusician")
                        .HasColumnType("int");

                    b.HasKey("IdTrack", "IdMusician");

                    b.HasIndex("IdMusician");

                    b.ToTable("Musician_Track");

                    b.HasData(
                        new
                        {
                            IdTrack = 1,
                            IdMusician = 1
                        },
                        new
                        {
                            IdTrack = 2,
                            IdMusician = 2
                        },
                        new
                        {
                            IdTrack = 3,
                            IdMusician = 3
                        },
                        new
                        {
                            IdTrack = 4,
                            IdMusician = 3
                        },
                        new
                        {
                            IdTrack = 5,
                            IdMusician = 1
                        },
                        new
                        {
                            IdTrack = 6,
                            IdMusician = 1
                        },
                        new
                        {
                            IdTrack = 7,
                            IdMusician = 2
                        },
                        new
                        {
                            IdTrack = 8,
                            IdMusician = 2
                        },
                        new
                        {
                            IdTrack = 9,
                            IdMusician = 4
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Track", b =>
                {
                    b.Property<int>("IdTrack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<int?>("IdMusicAlbum")
                        .HasColumnType("int");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("IdTrack");

                    b.HasIndex("IdMusicAlbum");

                    b.ToTable("Track");

                    b.HasData(
                        new
                        {
                            IdTrack = 1,
                            Duration = 3.3300000000000001,
                            IdMusicAlbum = 1,
                            TrackName = "Shadow"
                        },
                        new
                        {
                            IdTrack = 2,
                            Duration = 3.2000000000000002,
                            IdMusicAlbum = 1,
                            TrackName = "Eyes"
                        },
                        new
                        {
                            IdTrack = 3,
                            Duration = 2.5800000000000001,
                            IdMusicAlbum = 1,
                            TrackName = "Sunny"
                        },
                        new
                        {
                            IdTrack = 4,
                            Duration = 3.1800000000000002,
                            IdMusicAlbum = 2,
                            TrackName = "Ocean"
                        },
                        new
                        {
                            IdTrack = 5,
                            Duration = 2.5800000000000001,
                            IdMusicAlbum = 2,
                            TrackName = "Yellow"
                        },
                        new
                        {
                            IdTrack = 6,
                            Duration = 3.0800000000000001,
                            IdMusicAlbum = 2,
                            TrackName = "Thank you"
                        },
                        new
                        {
                            IdTrack = 7,
                            Duration = 3.1899999999999999,
                            IdMusicAlbum = 3,
                            TrackName = "Cake"
                        },
                        new
                        {
                            IdTrack = 8,
                            Duration = 2.5800000000000001,
                            IdMusicAlbum = 3,
                            TrackName = "Bye bye"
                        },
                        new
                        {
                            IdTrack = 9,
                            Duration = 3.1800000000000002,
                            TrackName = "Love"
                        });
                });

            modelBuilder.Entity("WebApplication.Models.Album", b =>
                {
                    b.HasOne("WebApplication.Models.MusicLabel", "MusicLabel")
                        .WithMany("Album")
                        .HasForeignKey("IdMusicLabel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication.Models.Musician_Track", b =>
                {
                    b.HasOne("WebApplication.Models.Musician", "Musician")
                        .WithMany("Musician_Track")
                        .HasForeignKey("IdMusician")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication.Models.Track", "Track")
                        .WithMany("Musician_Track")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication.Models.Track", b =>
                {
                    b.HasOne("WebApplication.Models.Album", "Album")
                        .WithMany("Track")
                        .HasForeignKey("IdMusicAlbum");
                });
#pragma warning restore 612, 618
        }
    }
}
